#!/bin/bash

. ~/.profile
type gw &> /dev/null && echo 'already installed, exiting' && exit -1

main() {
  source=$(declare -f gw)
  echo -e "\n$source" >> ~/.profile
  echo "gw installed, don't forget to source ~/.profile"
}

gw() {
    dir=$PWD;
    file=gradlew;
    while [[ ! -f "$dir/$file" && $dir != "/" ]]; do
      dir=$(cd $dir/.. && pwd)
    done;

    if [[ $dir == "/" ]]; then
      echo "error: could not find '$file' upwards and reached '$dir'.";
      return 1
    else
      $dir/$file $@
    fi
}
